server:
  port: 8282
  host: localhost
spring:
  output:
    ansi:
      enabled: ALWAYS
  application:
    name: payment-service
  security:
    oauth2:
      resourceserver:
        jwt:
paypal:
  clientId: AU0nJOUpFza2rkAqZdbaMxoUxGJqPc0YBPK59qiSsAQLgXBYCiZgz23Wi9-vj-EwHam4jGCN68YNvePQ
  clientSecret: EN2PrI8qAoEH6LBwjV-jYPdzrMLvU0VDGNflSrqnA2y9XQqfeNHq8B5HwCaM7whcqTS0R1yKpdrc3chO
  mode: live
security:
  corsAllowedOrigins: "http://localhost:8181"
  corsAllowedMethods: "GET, POST, PUT, DELETE"
  corsAllowedHeaders: "Authorization"
  permitAllPaths:
    - "/payment/**"

