server:
  port: 8282
  host: localhost
spring:
  output:
    ansi:
      enabled: ALWAYS
  application:
    name: payment-service
  security:
    oauth2:
      resourceserver:
        jwt:
paypal:
  clientId: AZihTqcVFX8MUNyRnI1cst_rAn7-lo5zgF3-CxCz9c1SZgXs7ESMzMnYvlcNGE_sdJNUCX3IIl1bGG9h
  clientSecret: EOBAgezq1iUsMxfKNKPRMGgTgOCKbjT2iDnTSmrfZif0U1gJblBrdz9-7MnhSRA5QjQNDhayYoXxqy_Z
  mode: sandbox
security:
  corsAllowedOrigins: "http://localhost:8181"
  corsAllowedMethods: "GET, POST, PUT, DELETE"
  corsAllowedHeaders: "Authorization"
  permitAllPaths:
    - "/payment/**"

